nelmio_api_doc:
    documentation:
        info:
            title: vetShopBackEnd
            description: This is app that offers scheduling appointments for pet health care.
            version: 1.0.0
    areas:
        path_patterns:
                - ^/