version: '3'
services:
  mysql:
    image: percona:8.0
    restart: always
    ports:
      - '3326:3306' # 'local_port:port_in_container'
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_RANDOM_ROOT_PASSWORD
#      - DB_HOST=127.0.0.1
      - MYSQL_DATABASE=vet_shop
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
#  mailer:
#    image: schickling/mailcatcher
#    ports: [ 1025, 1080 ]
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_vet_shop
    links:
      - mysql
    environment:
      PMA_HOST: vet_shop
      PMA_ARBITRARY: 1
      MYSQL_USERNAME: 'admin'
      MYSQL_ROOT_PASSWORD: 'password_pma'
    restart: always
    ports:
      - "8082:80"
