<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Examination;
use App\Tests\Unit\BaseTestCase;
use PHPUnit\Framework\TestCase;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class ExaminationTest extends BaseTestCase
{
    private Examination $mockExamination;

    protected function setUp(): void
    {
        parent::setUp();

        $this->mockExamination = $this->makeMockExamination();
    }

    public function testCreatedExamination(): void
    {
        self::assertEquals('mockExamination', $this->mockExamination->getName());
        self::assertEquals(1000, $this->mockExamination->getPrice());
        self::assertEquals(60, $this->mockExamination->getDuration());
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $this->em->close();
        $this->em = null;
    }
}
