controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /login_check

app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
#api_refresh_token:
#    path: /api/token/refresh
#    controller: gesdinet.jwtrefreshtoken::refresh
