<?php

namespace App\Tests\Unit\Controller;

use App\Entity\HealthRecord;
use App\Repository\HealthRecordRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Exception;
use Nebkam\FluentTest\RequestBuilder;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpKernel\KernelInterface;

class HealthRecordControllerTest extends WebTestCase
{
//    private EntityManagerInterface $em;

    private EntityManagerInterface $em;

    /**
     * @throws Exception
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSomething(): void
    {
        $client = static::createClient();
        $response = RequestBuilder::create($client)
            ->setMethod('GET')
            ->setUri('/user/%s/health_records','44');
        self::assertResponseIsSuccessful();
        self::assertResponseStatusCodeSame(200);
    }

    public function testCreateHealthRecord(): void
    {
        $client = static::createClient();
        $response = RequestBuilder::create($client)
            ->setMethod('POST')
            ->setUri('/health_record')
            ->setContent('
                {
                      "vet": 12,
                      "pet": 1,
                      "examination": 3,
                      "startedAt": "2024-09-07T10:12:00.393Z",
                      "finishedAt": "2024-09-07T12:35:00.393Z",
                      "comment": "gotta checc if everything is ok"
                }
            ')
            ->getResponse();
        self::assertResponseIsSuccessful();

        $em = $client->getContainer()->get('doctrine')->getManager();
        $healthRecord = $em->getRepository(HealthRecordRepository::class)->find($response->getJsonContent()["id"]);


        self::assertStringContainsString('gotta checc',$healthRecord->getStatus());
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }



}
